
#include <GLUT/glut.h>
#include <glpng/glpng.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>


void Display(void);
void Reshape(int, int);
void Timer(int);
void PutSprite(int, int, int, pngInfo *);
void Keyboard(unsigned char, int, int); //追加


//PNG画像を読み込むための変数
GLuint img[5], img_yuka, img_player, img_toge, img_title, img_clear, img_miss, img_setumei, img_goal, img_percent, img_number[10], img_toride, img_die;
pngInfo info[6], info_yuka, info_player, info_toge, info_title, info_clear, info_miss, info_setumei, info_goal, info_percent, info_number[10], info_toride, info_die;
int move=0;

//マップ
char map[17][211];

char easy[17][211]={
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEGEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYYYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYEEEEEEEEEEEEEEEYYYYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYYYEEYYEEEYYEEEEEEEEEYYYEEYYYYYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYYEEEYYYEEEYYYEEEEEEEYYYYYYYEEEEEEEEEEEEEEEEEEECEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYEEEEEEEEEEEEEEEEEEEEEEEEEEEYYYYEEEEEEEEEYYEYYYYYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYYEEYYEEEEEEEEEEEEEEEEEEEEEEEYYYEEEEEYYEEEYYYYEEEEEEEEEEEEYYYYYYYYEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEYYYEEYYEEEEEEYEEEEEEEYEEEEEEYYYEEEEEEETTYYYYYYYYEYYYYYYEEEEEEEEEYYEEYEEEEEEEEEEEEEEEEEEYYEEEEEEYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYYEEEYYYYYEEEEEEEEEEEYYYYYYYYYEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEETEEEEEEEEEEEYYYYYYYEEYYYEEEEEYEEEEEEEYYYYYTTYYYTTTTTTTYYYYYYYYYYEYYYYYYTTYYYYEEEYYTTYYYYYYYTTEEEETYYYYYYYTTTTTTYYEEEEEEEEEEEEEETEEEYYYYTTTTTTTTTYYEEEYYYYYTTTTTTTTTTTYYYYYYYYYYEEEEEEEEEEEEEYEEEEEEEEEEE\0",
    "YYYYYYYYYYYYYYYYYEEYYYYYYYYYYEEYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYEYYYYYYYYYYYYEEEYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYEEYYEYYYYYYYYYYYYYYYYYYYYYYYYYEEEYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0"
};


char normal[17][211]={
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYEEEEYEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYTTTTEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYYYYYYEEEEEEEEEEEEEEEEEEEEEEEEEETEEEEEEEEEEEEEEGEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYYYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEETTTTTTEEEEEEEEEEEEEYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYYYYEETTTTEETEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEETTEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYEEEEEEEEEEEEEEYYYYYEYYTEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEETTTTEEEEEEEYYYYYEEEEYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYYYYYYYYYEEEYEEEEEEEEEEEEEEYEEEEEEEEEEYYEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEYYYYYYEEEEEEEEEEEEEETTTTTEEEEEEEEEEEEEEEYYYEEEYYEEEEEEEEYYYYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEETTTTTTTTTEEEEEEEEEEEEEEYEEEEEEEEEEEEEEYYYEEEEEEEEEECEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEYYYYYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYYYEEEYYEEEEYYEEYYYYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEETEEEEEEEEEEEEETEEEEEEEEEEEEEEEEEEEEEEEYEEEEEEEEEEEEEEEEEEYYYYEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEYYYEEYYYYYYEEEEEEEEEEEEEEEEEEEEEEEEEEETYYYYYYYYYEEEYYYYYYYYEEYYYYYEEEEEEEEEYEEEEEEEEEEEEEEEEEEEEEEEEEEYEEEEEEEEYYYEEEEEEEEEEEEEYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYYYYYEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEETEEEEEEEYYYEEYYYYYYEEEEEEYYYTTEEEETEEEEYYEEYYYYYYYYYYYYYTTTYYYYYYYYEEYYYYYTTYYYYEEEYEEEEEYYYYETEEEETEEEEEETEEEEEETEEEEEEEEEETEEEEETEEEEEEEEEEEEEEEEEEEEEEEYYETEETTTTTTTTTTTTTTTTTTYYYYYYEEEEYEEEEEEEEEEE\0",
    "YYYYYYYYYYYYYYYYYYYYYEEYYYYYYYYYYEEYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYEEYYYYYYYYYYYEEEYYYYYYYYYYYYYYEEYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYEEYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0"
};


char hard[17][211]={
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEETEEEEEEEEEEEEEEEEEEEEEEETEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEETTTTEEEEEEEEEEEETTEEEEEEEEEEEEEEEEEEETTTTYYYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEGEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEETEEEEEEEEEEEEEEEEEEEEEEYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYEEEEEEEEEEEEEEEEEEEEEEEEYEEEEEYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYYYYYYYYEEEEEEEEEEEEEEEEEYYYYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEYEEEYEEEEEEEEEEEEEEEEEEEEEEYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYYYYYEEEEEEEEEEEEEEEEEEEEEEYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEYYYYYYTEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEYEEEEEEEYEYYEEEEEEEEEEEEEEEYEEEYYYYYEEEEEEEEEEEYEEEEEEEEEEYYYYYEEYYYYYEEEEEEEEEEEEEEEEEEEEYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEYYYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYYYYYYYEEEEEEEEEEEEEEEEEEECEEEEEEEE\0",
    "EEEEEEEEEEEEEEEYEEEYEEEEEEEYEEEEEEEEEEEEEEYEEEYEEEYEEEEEEEEEEEYEEEEEEEEEEEYYEYYYYYEEYYYYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYYYYEEEEEEEEEEEEYYYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYEEYYYYYYYYEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEYEEEYEEEYEEEEEEEYEEEEYYEEEYYEEEYEEEYEEEYEEEEEYYYEEEEEEETTYYYYYYYYEYYYYYEEYYYYYEEETYEEEEETEEEEEEEEEEEEEYYYTYYTYYYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYYEEEEEEEEEYYYYYYYYYEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEYTTTYTTTYEETTTTTYEEEEEEEEEYYTTTYTTTYTTTYTTTTTYYYTTTTTTTYYYYYYYYYYEYYYYYTTYYYYYEEEYYYYYYYYYYTTEEETYYYYYYYTTTTTYYYYEEEEEEEEEYYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYYEEEYYYYYYYYYYEETEEEEEEEEEEYEEEEEEEEEEE\0",
    "YYYYYYYYYYYYYYYYYYYYEEYYYYYYYYYYEEYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYEYYYYYYYYYYYYEEEYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYEEEEYYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEYTEEEEEEEEEEYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0",
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\0"
};




int X=192;
int Y=512;

int next=-100;

int chakuchi=0;
double jumptime=0;
int vo=0;  //初速度
int jumped=0;
int c=0;

int death=0;

int bamen=1;



int main(int argc, char **argv){

    int i;

    char gazou[30];


    //一般的な準備
    srandom(12345);
    glutInit(&argc, argv);
    glutInitWindowSize(960, 640);
    glutCreateWindow("BREAK YOUR HEART");
    glutInitDisplayMode(GLUT_RGBA | GLUT_ALPHA);
    glClearColor(0.0, 0.0, 0.0, 0.0);

    //テクスチャのアルファチャンネルを有効にする設定
    glEnable(GL_BLEND);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
    glTexEnvf(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_MODULATE);

    //PNG画像の読み込み
    img_yuka=pngBind("yuka.png", PNG_NOMIPMAP, PNG_ALPHA, &info_yuka, GL_CLAMP, GL_NEAREST, GL_NEAREST);
    img_player=pngBind("player.png", PNG_NOMIPMAP, PNG_ALPHA, &info_player, GL_CLAMP, GL_NEAREST, GL_NEAREST);
    img_toge=pngBind("toge.png", PNG_NOMIPMAP, PNG_ALPHA, &info_toge, GL_CLAMP, GL_NEAREST, GL_NEAREST);
    img_title=pngBind("title.png", PNG_NOMIPMAP, PNG_ALPHA, &info_title, GL_CLAMP, GL_NEAREST, GL_NEAREST);
    img_clear=pngBind("clear.png", PNG_NOMIPMAP, PNG_ALPHA, &info_clear, GL_CLAMP, GL_NEAREST, GL_NEAREST);
    img_miss=pngBind("miss.png", PNG_NOMIPMAP, PNG_ALPHA, &info_miss, GL_CLAMP, GL_NEAREST, GL_NEAREST);
    img_setumei=pngBind("setumei.png", PNG_NOMIPMAP, PNG_ALPHA, &info_setumei, GL_CLAMP, GL_NEAREST, GL_NEAREST);
    img_goal=pngBind("goal.png", PNG_NOMIPMAP, PNG_ALPHA, &info_goal, GL_CLAMP, GL_NEAREST, GL_NEAREST);
    img_percent=pngBind("percent.png", PNG_NOMIPMAP, PNG_ALPHA, &info_percent, GL_CLAMP, GL_NEAREST, GL_NEAREST);
    img_toride=pngBind("toride.png", PNG_NOMIPMAP, PNG_ALPHA, &info_toride, GL_CLAMP, GL_NEAREST, GL_NEAREST);
    img_die=pngBind("die.png", PNG_NOMIPMAP, PNG_ALPHA, &info_die, GL_CLAMP, GL_NEAREST, GL_NEAREST);

    for(i=0;i<10;i++){
        sprintf(gazou, "%d.png", i);
        img_number[i]=pngBind(gazou, PNG_NOMIPMAP, PNG_ALPHA, &info_number[i], GL_CLAMP, GL_NEAREST, GL_NEAREST);
    }





    //コールバック関数の登録
    glutDisplayFunc(Display);
    glutReshapeFunc(Reshape);
    glutTimerFunc(15, Timer, 0);
    glutKeyboardFunc(Keyboard);  //追加

    //イベントループ突入
    glutMainLoop();

    return 0;

}



//タイマー割り込みで画面を描画し直す

void Timer(int t){

    if(bamen==3){
        if(c<195){
            move+=4;
            if(move%64==0){
              c++;
              move=0;
            }
        }
        else bamen=4;

        jumptime+=0.015;
    }



    glutPostRedisplay();
    glutTimerFunc(15, Timer, 0);


}



//ウィンドウのサイズ変更が発生した時に座標系を再設計する関数

void Reshape(int w, int h){
  glViewport(0,0,w,h);
  glMatrixMode(GL_MODELVIEW);
  glLoadIdentity();
  gluOrtho2D(0, w, 0, h);
  glScaled(1, -1, 1);
  glTranslated(0, -h, 0);
}



//ウィンドウの表示内容を更新する

void Display(void){
    int x,y; //PNG画像をおく座標
    int w,h; //現在のウィンドウのサイズ

    int i,j;
    int pY;
    long double henni=0.0;
    int before;

    int juu,ichi;
    int sindo;

    before=Y;


    glClear(GL_COLOR_BUFFER_BIT);

    w=glutGet(GLUT_WINDOW_WIDTH);
    h=glutGet(GLUT_WINDOW_HEIGHT);


    if(bamen==1){
        PutSprite(img_title, 0, 0, &info_title);
    }

    if(bamen==2){
        y=0;
        for(i=5;i<15;i++){
            x=0;
            for(j=0;j<15;j++){



              if(map[i][j]=='Y') PutSprite(img_yuka, x, y, &info_yuka);
              else if(map[i][j]=='T') PutSprite(img_toge, x, y, &info_toge);

              x+=64;
            }
            y+=64;
        }

        PutSprite(img_setumei, 0, 0, &info_setumei);

    }

    if(bamen==3){
        y=0;
        for(i=5;i<15;i++){
            x=0;
            for(j=0+c;j<20+c;j++){

              if(map[i][j]=='Y') PutSprite(img_yuka, x-move, y, &info_yuka);
              else if(map[i][j]=='T') PutSprite(img_toge, x-move, y, &info_toge);
              else if(map[i][j]=='G') PutSprite(img_goal, x-move, y, &info_goal);
              else if(map[i][j]=='C') PutSprite(img_toride, x-move, y+36, &info_toride);

              x+=64;
            }
            y+=64;
        }


        if(jumped==1){
            Y-=16;
            if(move==0){

                if(map[(Y/64)+5][c+3]=='T'){
                    death=1;
                }

                if(map[Y/64+5][c+3]=='Y'){
                    jumped=0;
                    jumptime=0;
                    Y += 64-(Y%64);
                }

            }
            else{
                if(map[(Y/64)+5][c+3]=='T' || map[(Y/64)+5][c+4]=='T'){
                    death=1;
                }

                if(map[Y/64+5][c+3]=='Y' || map[Y/64+5][c+4]=='Y'){
                    jumped=0;
                    jumptime=0;
                    Y += 64-(Y%64);
                }

            }
        }


        pY=(int)Y/64;

        if(move==0){
            if(map[pY+6][3+c]=='T'){
                death=1;
            }

            if(map[pY+6][3+c]=='Y'){
              chakuchi=1;
              jumped=0;
              if(Y%64!=0){
                Y-=Y%64;
              }

            }
            else{

                if(chakuchi==1){
                  jumptime=0;
                  chakuchi=0;
                }

                henni=jumptime*39.2;
                Y+=(int)henni;

            }
        }
        else{
            if(map[pY+6][3+c]=='T' || map[pY+6][4+c]=='T'){
                death=1;
            }

            if(map[pY+6][3+c]=='Y' || map[pY+6][4+c]=='Y'){
              chakuchi=1;
              jumped=0;
              if(Y%64!=0){
                Y-=Y%64;
              }

            }
            else{

                if(chakuchi==1){
                  jumptime=0;
                  chakuchi=0;
                }


                henni=jumptime*39.2;
                Y+=(int)henni;

            }
        }



        if(next!=-100){
            Y=next;
            next=-100;
        }
        else{
            if(chakuchi==0){
                next=Y;
                if(jumped==1){
                    next-=16;
                }
                henni=(jumptime+0.015)*39.2;
                next+=(int)henni;
                if(next%64==0){
                    next=-100;
                }
                else{
                    if(move==0){
                        if(map[(next/64)+6][3+c]=='Y'){
                            next-=next%64;
                            jumped=0;
                        }
                        else if(map[(next/64)+6][3+c]=='T'){
                            next-=next%64;
                            jumped=0;
                        }
                        else next=-100;
                    }
                    else{
                        if(map[(next/64)+6][3+c]=='Y' || map[(next/64)+6][4+c]=='Y'){
                            next-=next%64;
                            jumped=0;
                        }
                        else if(map[(next/64)+6][3+c]=='T' || map[(next/64)+6][4+c]=='T'){
                            next-=next%64;
                            jumped=0;
                        }
                        else next=-100;
                    }
                }
            }


        }


        if(Y>640){
            death=1;
        }


        if(Y%64==0){
            if(move==0){
                if(map[Y/64+5][c+4]!='E'){
                    death=1;
                }
            }
        }
        else{
            if(move==0){
                if(map[Y/64+5][c+4]!='E' || map[(Y/64)+6][c+4]!='E'){
                    death=1;
                }
            }
        }

        if(death==1){
            Y=before;
        }







        if(death==1) PutSprite(img_die, X, Y, &info_die);
        else PutSprite(img_player, X, Y, &info_player);


    }


    if(bamen==4){
        PutSprite(img_clear, 0, 0, &info_clear);
    }

    if(bamen==5){
        PutSprite(img_miss, 0, 0, &info_miss);

        sindo=c*100/195;
        juu=sindo/10;
        ichi=sindo-(juu*10);
        if(juu!=0){
            PutSprite(img_number[juu], 402, 240, &info_number[juu]);
        }
        PutSprite(img_number[ichi], 466, 240, &info_number[ichi]);
        PutSprite(img_percent, 562, 240, &info_percent);
    }



    glFlush();


    if(death==1){
        sleep(1);
        death=0;
        bamen=5;
    }

}



//num版のPNG画像を座標(x,y)に表示する

void PutSprite(int num, int x, int y, pngInfo *info){

  int w, h; //テクスチャの幅と高さ


  w=info->Width; //テクスチャの幅と高さを取得する
  h=info->Height;

  glPushMatrix();
  glEnable(GL_TEXTURE_2D);
  glBindTexture(GL_TEXTURE_2D, num);
  glColor4ub(255, 255, 255, 255);

  glBegin(GL_QUADS); // 幅w, 高さhの四角形

  glTexCoord2i(0, 0);
  glVertex2i(x,y);

  glTexCoord2i(0,1);
  glVertex2i(x, y+h);

  glTexCoord2i(1, 1);
  glVertex2i(x+w, y+h);

  glTexCoord2i(1, 0);
  glVertex2i(x+w, y);

  glEnd();

  glDisable(GL_TEXTURE_2D);
  glPopMatrix();

}



//キー入力の処理

void Keyboard(unsigned char key, int x, int y){

    int i;

    if(bamen==1){
        if(key=='e' || key=='E'){
            for(i=0;i<17;i++){
                strcpy(map[i],easy[i]);
            }
            bamen=2;
        }
        if(key=='n' || key=='N'){
            for(i=0;i<17;i++){
                strcpy(map[i],normal[i]);
            }
            bamen=2;
        }
        if(key=='h' || key=='H'){
            for(i=0;i<17;i++){
                strcpy(map[i],hard[i]);
            }
            bamen=2;
        }
    }

    if(bamen==2){

        X=192;
        Y=512;
        next=-100;
        chakuchi=0;
        jumptime=0;
        vo=0;  //初速度
        jumped=0;
        c=0;
        death=0;


        if(key==32) bamen=3;
    }

    if(bamen==3){
      if(key==32){


        if(chakuchi==1){
          jumptime=0;
          chakuchi=0;

          jumped=1;

        }
      }
    }

    if(bamen==4){
        if(key=='t' || key=='T') bamen=1;
        if(key=='n' || key=='N') bamen=2;
    }


    if(bamen==5){
        if(key=='t' || key=='T') bamen=1;
        if(key=='n' || key=='N') bamen=2;
    }


    if(key==27) exit(0);



}
